stages:
  load_data:
    cmd: python src/stage_02_load_data.py --config=params.yaml
    deps:
    - src/stage_01_get_data.py
    - src/stage_02_load_data.py
    - data/raw/train.csv
    outs:
    - data/processed/train.csv

  split_data:
    cmd: python src/stage_03_split_data.py --config=params.yaml
    deps:
    - src/stage_03_split_data.py
    - data/processed/train.csv
    outs:
    - data/processed/train_predictive_maint.csv
    - data/processed/test_predictive_maint.csv 

  train_and_evaluate:
    cmd: python src/stage_04_train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_predictive_maint.csv
    - data/processed/test_predictive_maint.csv 
    - src/stage_04_train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.max_features
    - estimators.RandomForestRegressor.params.min_samples_split
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib